version: 2.1

orbs:
  nx: nrwl/nx@1.6.1
  continuation: circleci/continuation@0.3.1

setup: true

parameters:
  affected-list:
    description: Path to the file where the affected list of apps is generated
    type: string
    default: affected-list.txt

references:
  setup_env_node: &setup_env_node
    docker:
      - image: cimg/node:18.10.0
  attach_workspace: &attach_workspace
    at: ~/project
  nx/set-shas: &nx_set_shas_option
    error-on-no-successful-workflow: false
    main-branch-name: main
    workflow-name: build-and-release
  save_node_cache: &save_node_cache
    key: node-module-cache-{{ checksum "./yarn.lock" }}
    paths:
      - node_modules
  restore_node_cache: &restore_node_cache
    keys:
      - node-module-cache-{{ checksum "./yarn.lock" }}

jobs:
  install-dependencies:
    <<: *setup_env_node
    steps:
      - checkout
      - restore_cache: *restore_node_cache
      - run: yarn --frozen-lockfile
      - save_cache: *save_node_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    <<: *setup_env_node
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - nx/set-shas: *nx_set_shas_option
      - run: yarn nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --parallel --max-parallel=3

  lint:
    <<: *setup_env_node
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - nx/set-shas: *nx_set_shas_option
      - run: yarn nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD --parallel --max-parallel=3

  affected-apps:
    <<: *setup_env_node
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - nx/set-shas: *nx_set_shas_option
      - run:
          name: Generate the list of apps having changes
          command: |
            touch << parameters.output-file >>

            # Using https://nx.dev/nx/affected#base and https://nx.dev/nx/affected#head options for nx to compute diffs and determine which apps changes
            AFFECTED_RAW=$(npx nx affected:apps --base=$NX_BASE --head=$NX_HEAD --plain)
            IFS=' ' read -ra APPS \<<< "$AFFECTED_RAW"

            # Store list in file to be passed to following jobs
            for app in "${APPS[@]}"; do
              echo "apps/$app" >> << parameters.affected-list >>
            done

            # Print affected apps
            cat << parameters.affected-list >>

#  build:
#    <<: *setup_env_node
#    steps:
#      - checkout
#      - attach_workspace: *attach_workspace
#      - nx/set-shas: *nx_set_shas_option
#      - run: mkdir dist
#      - run: yarn nx affected --target=build --base=$NX_BASE --head=$NX_HEAD --parallel --max-parallel=3
#      - persist_to_workspace:
#          root: .
#          paths:
#            - dist

  continuation:
    <<: *setup_env_node
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - nx/set-shas: *nx_set_shas_option
      - run: echo "continuation"

workflows:
  build-and-release:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
      - continuation:
          filters:
            branches:
              only:
                - main
          requires:
            - lint
            - test
            - build
