export enum GraphQLContextEnum {
  USER_DATA_LOADER = 'USER_DATA_LOADER',
  WISHLIST_DATA_LOADER = 'WISHLIST_DATA_LOADER',
  EVENT_DATA_LOADER = 'EVENT_DATA_LOADER',
  EVENT_ATTENDEE_DATA_LOADER = 'EVENT_ATTENDEE_DATA_LOADER',
}
