services:
  db:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_USER: "service"
      POSTGRES_PASSWORD: "service"
      POSTGRES_DB: "wishlist-api"
    healthcheck:
      test: "pg_isready -d wishlist-api -U service"
      interval: 2s
      timeout: 5s
      retries: 10

  mail:
    image: maildev/maildev:2.2.1
    healthcheck:
      test: wget --spider http://localhost:1080 || exit 1
      interval: 2s
      timeout: 5s
      retries: 10

  valkey:
    image: valkey/valkey:8.0-alpine
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10
