/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AnonymousWithLayoutRouteImport } from './routes/_anonymous-with-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedWithLayoutRouteImport } from './routes/_authenticated/_with-layout'
import { Route as AnonymousWithLayoutRegisterRouteImport } from './routes/_anonymous-with-layout/register'
import { Route as AnonymousWithLayoutLoginRouteImport } from './routes/_anonymous-with-layout/login'
import { Route as AnonymousWithLayoutConfirmEmailChangeRouteImport } from './routes/_anonymous-with-layout/confirm-email-change'
import { Route as AnonymousWithLayoutForgotPasswordIndexRouteImport } from './routes/_anonymous-with-layout/forgot-password/index'
import { Route as AuthenticatedWithLayoutAdminRouteImport } from './routes/_authenticated/_with-layout/admin'
import { Route as AnonymousWithLayoutForgotPasswordRenewRouteImport } from './routes/_anonymous-with-layout/forgot-password/renew'
import { Route as AuthenticatedWithLayoutWishlistsIndexRouteImport } from './routes/_authenticated/_with-layout/wishlists/index'
import { Route as AuthenticatedWithLayoutEventsIndexRouteImport } from './routes/_authenticated/_with-layout/events/index'
import { Route as AuthenticatedWithLayoutAdminIndexRouteImport } from './routes/_authenticated/_with-layout/admin/index'
import { Route as AuthenticatedWithLayoutWishlistsNewRouteImport } from './routes/_authenticated/_with-layout/wishlists/new'
import { Route as AuthenticatedWithLayoutUserProfileRouteImport } from './routes/_authenticated/_with-layout/user/profile'
import { Route as AuthenticatedWithLayoutEventsNewRouteImport } from './routes/_authenticated/_with-layout/events/new'
import { Route as AuthenticatedWithLayoutWishlistsWishlistIdIndexRouteImport } from './routes/_authenticated/_with-layout/wishlists/$wishlistId/index'
import { Route as AuthenticatedWithLayoutEventsEventIdIndexRouteImport } from './routes/_authenticated/_with-layout/events/$eventId/index'
import { Route as AuthenticatedWithLayoutAdminUsersIndexRouteImport } from './routes/_authenticated/_with-layout/admin/users/index'
import { Route as AuthenticatedWithLayoutAdminEventsIndexRouteImport } from './routes/_authenticated/_with-layout/admin/events/index'
import { Route as AuthenticatedWithLayoutWishlistsWishlistIdEditRouteImport } from './routes/_authenticated/_with-layout/wishlists/$wishlistId/edit'
import { Route as AuthenticatedWithLayoutEventsEventIdEditRouteImport } from './routes/_authenticated/_with-layout/events/$eventId/edit'
import { Route as AuthenticatedWithLayoutAdminUsersUserIdRouteImport } from './routes/_authenticated/_with-layout/admin/users/$userId'
import { Route as AuthenticatedWithLayoutAdminEventsEventIdRouteImport } from './routes/_authenticated/_with-layout/admin/events/$eventId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousWithLayoutRoute = AnonymousWithLayoutRouteImport.update({
  id: '/_anonymous-with-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWithLayoutRoute = AuthenticatedWithLayoutRouteImport.update({
  id: '/_with-layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AnonymousWithLayoutRegisterRoute =
  AnonymousWithLayoutRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AnonymousWithLayoutRoute,
  } as any)
const AnonymousWithLayoutLoginRoute =
  AnonymousWithLayoutLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => AnonymousWithLayoutRoute,
  } as any)
const AnonymousWithLayoutConfirmEmailChangeRoute =
  AnonymousWithLayoutConfirmEmailChangeRouteImport.update({
    id: '/confirm-email-change',
    path: '/confirm-email-change',
    getParentRoute: () => AnonymousWithLayoutRoute,
  } as any)
const AnonymousWithLayoutForgotPasswordIndexRoute =
  AnonymousWithLayoutForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => AnonymousWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutAdminRoute =
  AuthenticatedWithLayoutAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AnonymousWithLayoutForgotPasswordRenewRoute =
  AnonymousWithLayoutForgotPasswordRenewRouteImport.update({
    id: '/forgot-password/renew',
    path: '/forgot-password/renew',
    getParentRoute: () => AnonymousWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutWishlistsIndexRoute =
  AuthenticatedWithLayoutWishlistsIndexRouteImport.update({
    id: '/wishlists/',
    path: '/wishlists/',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutEventsIndexRoute =
  AuthenticatedWithLayoutEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutAdminIndexRoute =
  AuthenticatedWithLayoutAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWithLayoutAdminRoute,
  } as any)
const AuthenticatedWithLayoutWishlistsNewRoute =
  AuthenticatedWithLayoutWishlistsNewRouteImport.update({
    id: '/wishlists/new',
    path: '/wishlists/new',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutUserProfileRoute =
  AuthenticatedWithLayoutUserProfileRouteImport.update({
    id: '/user/profile',
    path: '/user/profile',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutEventsNewRoute =
  AuthenticatedWithLayoutEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute =
  AuthenticatedWithLayoutWishlistsWishlistIdIndexRouteImport.update({
    id: '/wishlists/$wishlistId/',
    path: '/wishlists/$wishlistId/',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutEventsEventIdIndexRoute =
  AuthenticatedWithLayoutEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutAdminUsersIndexRoute =
  AuthenticatedWithLayoutAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedWithLayoutAdminRoute,
  } as any)
const AuthenticatedWithLayoutAdminEventsIndexRoute =
  AuthenticatedWithLayoutAdminEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedWithLayoutAdminRoute,
  } as any)
const AuthenticatedWithLayoutWishlistsWishlistIdEditRoute =
  AuthenticatedWithLayoutWishlistsWishlistIdEditRouteImport.update({
    id: '/wishlists/$wishlistId/edit',
    path: '/wishlists/$wishlistId/edit',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutEventsEventIdEditRoute =
  AuthenticatedWithLayoutEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => AuthenticatedWithLayoutRoute,
  } as any)
const AuthenticatedWithLayoutAdminUsersUserIdRoute =
  AuthenticatedWithLayoutAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedWithLayoutAdminRoute,
  } as any)
const AuthenticatedWithLayoutAdminEventsEventIdRoute =
  AuthenticatedWithLayoutAdminEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedWithLayoutAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/confirm-email-change': typeof AnonymousWithLayoutConfirmEmailChangeRoute
  '/login': typeof AnonymousWithLayoutLoginRoute
  '/register': typeof AnonymousWithLayoutRegisterRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/forgot-password/renew': typeof AnonymousWithLayoutForgotPasswordRenewRoute
  '/admin': typeof AuthenticatedWithLayoutAdminRouteWithChildren
  '/forgot-password': typeof AnonymousWithLayoutForgotPasswordIndexRoute
  '/events/new': typeof AuthenticatedWithLayoutEventsNewRoute
  '/user/profile': typeof AuthenticatedWithLayoutUserProfileRoute
  '/wishlists/new': typeof AuthenticatedWithLayoutWishlistsNewRoute
  '/admin/': typeof AuthenticatedWithLayoutAdminIndexRoute
  '/events': typeof AuthenticatedWithLayoutEventsIndexRoute
  '/wishlists': typeof AuthenticatedWithLayoutWishlistsIndexRoute
  '/admin/events/$eventId': typeof AuthenticatedWithLayoutAdminEventsEventIdRoute
  '/admin/users/$userId': typeof AuthenticatedWithLayoutAdminUsersUserIdRoute
  '/events/$eventId/edit': typeof AuthenticatedWithLayoutEventsEventIdEditRoute
  '/wishlists/$wishlistId/edit': typeof AuthenticatedWithLayoutWishlistsWishlistIdEditRoute
  '/admin/events': typeof AuthenticatedWithLayoutAdminEventsIndexRoute
  '/admin/users': typeof AuthenticatedWithLayoutAdminUsersIndexRoute
  '/events/$eventId': typeof AuthenticatedWithLayoutEventsEventIdIndexRoute
  '/wishlists/$wishlistId': typeof AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/confirm-email-change': typeof AnonymousWithLayoutConfirmEmailChangeRoute
  '/login': typeof AnonymousWithLayoutLoginRoute
  '/register': typeof AnonymousWithLayoutRegisterRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/forgot-password/renew': typeof AnonymousWithLayoutForgotPasswordRenewRoute
  '/forgot-password': typeof AnonymousWithLayoutForgotPasswordIndexRoute
  '/events/new': typeof AuthenticatedWithLayoutEventsNewRoute
  '/user/profile': typeof AuthenticatedWithLayoutUserProfileRoute
  '/wishlists/new': typeof AuthenticatedWithLayoutWishlistsNewRoute
  '/admin': typeof AuthenticatedWithLayoutAdminIndexRoute
  '/events': typeof AuthenticatedWithLayoutEventsIndexRoute
  '/wishlists': typeof AuthenticatedWithLayoutWishlistsIndexRoute
  '/admin/events/$eventId': typeof AuthenticatedWithLayoutAdminEventsEventIdRoute
  '/admin/users/$userId': typeof AuthenticatedWithLayoutAdminUsersUserIdRoute
  '/events/$eventId/edit': typeof AuthenticatedWithLayoutEventsEventIdEditRoute
  '/wishlists/$wishlistId/edit': typeof AuthenticatedWithLayoutWishlistsWishlistIdEditRoute
  '/admin/events': typeof AuthenticatedWithLayoutAdminEventsIndexRoute
  '/admin/users': typeof AuthenticatedWithLayoutAdminUsersIndexRoute
  '/events/$eventId': typeof AuthenticatedWithLayoutEventsEventIdIndexRoute
  '/wishlists/$wishlistId': typeof AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_anonymous-with-layout': typeof AnonymousWithLayoutRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_anonymous-with-layout/confirm-email-change': typeof AnonymousWithLayoutConfirmEmailChangeRoute
  '/_anonymous-with-layout/login': typeof AnonymousWithLayoutLoginRoute
  '/_anonymous-with-layout/register': typeof AnonymousWithLayoutRegisterRoute
  '/_authenticated/_with-layout': typeof AuthenticatedWithLayoutRouteWithChildren
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_anonymous-with-layout/forgot-password/renew': typeof AnonymousWithLayoutForgotPasswordRenewRoute
  '/_authenticated/_with-layout/admin': typeof AuthenticatedWithLayoutAdminRouteWithChildren
  '/_anonymous-with-layout/forgot-password/': typeof AnonymousWithLayoutForgotPasswordIndexRoute
  '/_authenticated/_with-layout/events/new': typeof AuthenticatedWithLayoutEventsNewRoute
  '/_authenticated/_with-layout/user/profile': typeof AuthenticatedWithLayoutUserProfileRoute
  '/_authenticated/_with-layout/wishlists/new': typeof AuthenticatedWithLayoutWishlistsNewRoute
  '/_authenticated/_with-layout/admin/': typeof AuthenticatedWithLayoutAdminIndexRoute
  '/_authenticated/_with-layout/events/': typeof AuthenticatedWithLayoutEventsIndexRoute
  '/_authenticated/_with-layout/wishlists/': typeof AuthenticatedWithLayoutWishlistsIndexRoute
  '/_authenticated/_with-layout/admin/events/$eventId': typeof AuthenticatedWithLayoutAdminEventsEventIdRoute
  '/_authenticated/_with-layout/admin/users/$userId': typeof AuthenticatedWithLayoutAdminUsersUserIdRoute
  '/_authenticated/_with-layout/events/$eventId/edit': typeof AuthenticatedWithLayoutEventsEventIdEditRoute
  '/_authenticated/_with-layout/wishlists/$wishlistId/edit': typeof AuthenticatedWithLayoutWishlistsWishlistIdEditRoute
  '/_authenticated/_with-layout/admin/events/': typeof AuthenticatedWithLayoutAdminEventsIndexRoute
  '/_authenticated/_with-layout/admin/users/': typeof AuthenticatedWithLayoutAdminUsersIndexRoute
  '/_authenticated/_with-layout/events/$eventId/': typeof AuthenticatedWithLayoutEventsEventIdIndexRoute
  '/_authenticated/_with-layout/wishlists/$wishlistId/': typeof AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/confirm-email-change'
    | '/login'
    | '/register'
    | '/welcome'
    | '/forgot-password/renew'
    | '/admin'
    | '/forgot-password'
    | '/events/new'
    | '/user/profile'
    | '/wishlists/new'
    | '/admin/'
    | '/events'
    | '/wishlists'
    | '/admin/events/$eventId'
    | '/admin/users/$userId'
    | '/events/$eventId/edit'
    | '/wishlists/$wishlistId/edit'
    | '/admin/events'
    | '/admin/users'
    | '/events/$eventId'
    | '/wishlists/$wishlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/confirm-email-change'
    | '/login'
    | '/register'
    | '/welcome'
    | '/forgot-password/renew'
    | '/forgot-password'
    | '/events/new'
    | '/user/profile'
    | '/wishlists/new'
    | '/admin'
    | '/events'
    | '/wishlists'
    | '/admin/events/$eventId'
    | '/admin/users/$userId'
    | '/events/$eventId/edit'
    | '/wishlists/$wishlistId/edit'
    | '/admin/events'
    | '/admin/users'
    | '/events/$eventId'
    | '/wishlists/$wishlistId'
  id:
    | '__root__'
    | '/'
    | '/_anonymous-with-layout'
    | '/_authenticated'
    | '/privacy'
    | '/terms'
    | '/_anonymous-with-layout/confirm-email-change'
    | '/_anonymous-with-layout/login'
    | '/_anonymous-with-layout/register'
    | '/_authenticated/_with-layout'
    | '/_authenticated/welcome'
    | '/_anonymous-with-layout/forgot-password/renew'
    | '/_authenticated/_with-layout/admin'
    | '/_anonymous-with-layout/forgot-password/'
    | '/_authenticated/_with-layout/events/new'
    | '/_authenticated/_with-layout/user/profile'
    | '/_authenticated/_with-layout/wishlists/new'
    | '/_authenticated/_with-layout/admin/'
    | '/_authenticated/_with-layout/events/'
    | '/_authenticated/_with-layout/wishlists/'
    | '/_authenticated/_with-layout/admin/events/$eventId'
    | '/_authenticated/_with-layout/admin/users/$userId'
    | '/_authenticated/_with-layout/events/$eventId/edit'
    | '/_authenticated/_with-layout/wishlists/$wishlistId/edit'
    | '/_authenticated/_with-layout/admin/events/'
    | '/_authenticated/_with-layout/admin/users/'
    | '/_authenticated/_with-layout/events/$eventId/'
    | '/_authenticated/_with-layout/wishlists/$wishlistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonymousWithLayoutRoute: typeof AnonymousWithLayoutRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous-with-layout': {
      id: '/_anonymous-with-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AnonymousWithLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_with-layout': {
      id: '/_authenticated/_with-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedWithLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_anonymous-with-layout/register': {
      id: '/_anonymous-with-layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AnonymousWithLayoutRegisterRouteImport
      parentRoute: typeof AnonymousWithLayoutRoute
    }
    '/_anonymous-with-layout/login': {
      id: '/_anonymous-with-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AnonymousWithLayoutLoginRouteImport
      parentRoute: typeof AnonymousWithLayoutRoute
    }
    '/_anonymous-with-layout/confirm-email-change': {
      id: '/_anonymous-with-layout/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/confirm-email-change'
      preLoaderRoute: typeof AnonymousWithLayoutConfirmEmailChangeRouteImport
      parentRoute: typeof AnonymousWithLayoutRoute
    }
    '/_anonymous-with-layout/forgot-password/': {
      id: '/_anonymous-with-layout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AnonymousWithLayoutForgotPasswordIndexRouteImport
      parentRoute: typeof AnonymousWithLayoutRoute
    }
    '/_authenticated/_with-layout/admin': {
      id: '/_authenticated/_with-layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedWithLayoutAdminRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_anonymous-with-layout/forgot-password/renew': {
      id: '/_anonymous-with-layout/forgot-password/renew'
      path: '/forgot-password/renew'
      fullPath: '/forgot-password/renew'
      preLoaderRoute: typeof AnonymousWithLayoutForgotPasswordRenewRouteImport
      parentRoute: typeof AnonymousWithLayoutRoute
    }
    '/_authenticated/_with-layout/wishlists/': {
      id: '/_authenticated/_with-layout/wishlists/'
      path: '/wishlists'
      fullPath: '/wishlists'
      preLoaderRoute: typeof AuthenticatedWithLayoutWishlistsIndexRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/events/': {
      id: '/_authenticated/_with-layout/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedWithLayoutEventsIndexRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/admin/': {
      id: '/_authenticated/_with-layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedWithLayoutAdminIndexRouteImport
      parentRoute: typeof AuthenticatedWithLayoutAdminRoute
    }
    '/_authenticated/_with-layout/wishlists/new': {
      id: '/_authenticated/_with-layout/wishlists/new'
      path: '/wishlists/new'
      fullPath: '/wishlists/new'
      preLoaderRoute: typeof AuthenticatedWithLayoutWishlistsNewRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/user/profile': {
      id: '/_authenticated/_with-layout/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof AuthenticatedWithLayoutUserProfileRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/events/new': {
      id: '/_authenticated/_with-layout/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedWithLayoutEventsNewRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/wishlists/$wishlistId/': {
      id: '/_authenticated/_with-layout/wishlists/$wishlistId/'
      path: '/wishlists/$wishlistId'
      fullPath: '/wishlists/$wishlistId'
      preLoaderRoute: typeof AuthenticatedWithLayoutWishlistsWishlistIdIndexRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/events/$eventId/': {
      id: '/_authenticated/_with-layout/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedWithLayoutEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/admin/users/': {
      id: '/_authenticated/_with-layout/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedWithLayoutAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedWithLayoutAdminRoute
    }
    '/_authenticated/_with-layout/admin/events/': {
      id: '/_authenticated/_with-layout/admin/events/'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedWithLayoutAdminEventsIndexRouteImport
      parentRoute: typeof AuthenticatedWithLayoutAdminRoute
    }
    '/_authenticated/_with-layout/wishlists/$wishlistId/edit': {
      id: '/_authenticated/_with-layout/wishlists/$wishlistId/edit'
      path: '/wishlists/$wishlistId/edit'
      fullPath: '/wishlists/$wishlistId/edit'
      preLoaderRoute: typeof AuthenticatedWithLayoutWishlistsWishlistIdEditRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/events/$eventId/edit': {
      id: '/_authenticated/_with-layout/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedWithLayoutEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedWithLayoutRoute
    }
    '/_authenticated/_with-layout/admin/users/$userId': {
      id: '/_authenticated/_with-layout/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedWithLayoutAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedWithLayoutAdminRoute
    }
    '/_authenticated/_with-layout/admin/events/$eventId': {
      id: '/_authenticated/_with-layout/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AuthenticatedWithLayoutAdminEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedWithLayoutAdminRoute
    }
  }
}

interface AnonymousWithLayoutRouteChildren {
  AnonymousWithLayoutConfirmEmailChangeRoute: typeof AnonymousWithLayoutConfirmEmailChangeRoute
  AnonymousWithLayoutLoginRoute: typeof AnonymousWithLayoutLoginRoute
  AnonymousWithLayoutRegisterRoute: typeof AnonymousWithLayoutRegisterRoute
  AnonymousWithLayoutForgotPasswordRenewRoute: typeof AnonymousWithLayoutForgotPasswordRenewRoute
  AnonymousWithLayoutForgotPasswordIndexRoute: typeof AnonymousWithLayoutForgotPasswordIndexRoute
}

const AnonymousWithLayoutRouteChildren: AnonymousWithLayoutRouteChildren = {
  AnonymousWithLayoutConfirmEmailChangeRoute:
    AnonymousWithLayoutConfirmEmailChangeRoute,
  AnonymousWithLayoutLoginRoute: AnonymousWithLayoutLoginRoute,
  AnonymousWithLayoutRegisterRoute: AnonymousWithLayoutRegisterRoute,
  AnonymousWithLayoutForgotPasswordRenewRoute:
    AnonymousWithLayoutForgotPasswordRenewRoute,
  AnonymousWithLayoutForgotPasswordIndexRoute:
    AnonymousWithLayoutForgotPasswordIndexRoute,
}

const AnonymousWithLayoutRouteWithChildren =
  AnonymousWithLayoutRoute._addFileChildren(AnonymousWithLayoutRouteChildren)

interface AuthenticatedWithLayoutAdminRouteChildren {
  AuthenticatedWithLayoutAdminIndexRoute: typeof AuthenticatedWithLayoutAdminIndexRoute
  AuthenticatedWithLayoutAdminEventsEventIdRoute: typeof AuthenticatedWithLayoutAdminEventsEventIdRoute
  AuthenticatedWithLayoutAdminUsersUserIdRoute: typeof AuthenticatedWithLayoutAdminUsersUserIdRoute
  AuthenticatedWithLayoutAdminEventsIndexRoute: typeof AuthenticatedWithLayoutAdminEventsIndexRoute
  AuthenticatedWithLayoutAdminUsersIndexRoute: typeof AuthenticatedWithLayoutAdminUsersIndexRoute
}

const AuthenticatedWithLayoutAdminRouteChildren: AuthenticatedWithLayoutAdminRouteChildren =
  {
    AuthenticatedWithLayoutAdminIndexRoute:
      AuthenticatedWithLayoutAdminIndexRoute,
    AuthenticatedWithLayoutAdminEventsEventIdRoute:
      AuthenticatedWithLayoutAdminEventsEventIdRoute,
    AuthenticatedWithLayoutAdminUsersUserIdRoute:
      AuthenticatedWithLayoutAdminUsersUserIdRoute,
    AuthenticatedWithLayoutAdminEventsIndexRoute:
      AuthenticatedWithLayoutAdminEventsIndexRoute,
    AuthenticatedWithLayoutAdminUsersIndexRoute:
      AuthenticatedWithLayoutAdminUsersIndexRoute,
  }

const AuthenticatedWithLayoutAdminRouteWithChildren =
  AuthenticatedWithLayoutAdminRoute._addFileChildren(
    AuthenticatedWithLayoutAdminRouteChildren,
  )

interface AuthenticatedWithLayoutRouteChildren {
  AuthenticatedWithLayoutAdminRoute: typeof AuthenticatedWithLayoutAdminRouteWithChildren
  AuthenticatedWithLayoutEventsNewRoute: typeof AuthenticatedWithLayoutEventsNewRoute
  AuthenticatedWithLayoutUserProfileRoute: typeof AuthenticatedWithLayoutUserProfileRoute
  AuthenticatedWithLayoutWishlistsNewRoute: typeof AuthenticatedWithLayoutWishlistsNewRoute
  AuthenticatedWithLayoutEventsIndexRoute: typeof AuthenticatedWithLayoutEventsIndexRoute
  AuthenticatedWithLayoutWishlistsIndexRoute: typeof AuthenticatedWithLayoutWishlistsIndexRoute
  AuthenticatedWithLayoutEventsEventIdEditRoute: typeof AuthenticatedWithLayoutEventsEventIdEditRoute
  AuthenticatedWithLayoutWishlistsWishlistIdEditRoute: typeof AuthenticatedWithLayoutWishlistsWishlistIdEditRoute
  AuthenticatedWithLayoutEventsEventIdIndexRoute: typeof AuthenticatedWithLayoutEventsEventIdIndexRoute
  AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute: typeof AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute
}

const AuthenticatedWithLayoutRouteChildren: AuthenticatedWithLayoutRouteChildren =
  {
    AuthenticatedWithLayoutAdminRoute:
      AuthenticatedWithLayoutAdminRouteWithChildren,
    AuthenticatedWithLayoutEventsNewRoute:
      AuthenticatedWithLayoutEventsNewRoute,
    AuthenticatedWithLayoutUserProfileRoute:
      AuthenticatedWithLayoutUserProfileRoute,
    AuthenticatedWithLayoutWishlistsNewRoute:
      AuthenticatedWithLayoutWishlistsNewRoute,
    AuthenticatedWithLayoutEventsIndexRoute:
      AuthenticatedWithLayoutEventsIndexRoute,
    AuthenticatedWithLayoutWishlistsIndexRoute:
      AuthenticatedWithLayoutWishlistsIndexRoute,
    AuthenticatedWithLayoutEventsEventIdEditRoute:
      AuthenticatedWithLayoutEventsEventIdEditRoute,
    AuthenticatedWithLayoutWishlistsWishlistIdEditRoute:
      AuthenticatedWithLayoutWishlistsWishlistIdEditRoute,
    AuthenticatedWithLayoutEventsEventIdIndexRoute:
      AuthenticatedWithLayoutEventsEventIdIndexRoute,
    AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute:
      AuthenticatedWithLayoutWishlistsWishlistIdIndexRoute,
  }

const AuthenticatedWithLayoutRouteWithChildren =
  AuthenticatedWithLayoutRoute._addFileChildren(
    AuthenticatedWithLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWithLayoutRoute: typeof AuthenticatedWithLayoutRouteWithChildren
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWithLayoutRoute: AuthenticatedWithLayoutRouteWithChildren,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonymousWithLayoutRoute: AnonymousWithLayoutRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
