query SecretSantaListPage($filters: PaginationFilters!) {
  mySecretSantas(filters: $filters) {
    __typename
    ... on GetSecretSantasPagedResponse {
      data {
        id
        status
        budget
        description
        users {
          id
        }
        event {
          id
          title
          icon
          eventDate
        }
      }
      pagination {
        totalPages
        totalElements
        pageNumber
        pageSize
      }
    }
  }
}

query SecretSantaListPageGetAdminEvents($filters: EventPaginationFilters!) {
  events(filters: $filters) {
    __typename
    ... on GetEventsPagedResponse {
      data {
        id
        title
        icon
        eventDate
        attendees {
          role
          user {
            id
          }
        }
        secretSanta {
          id
        }
      }
    }
  }
}
