scalar UserAccountId
scalar UserId
scalar UserRefreshTokenId

enum UserAccountProvider {
  PASSWORD
  GOOGLE
  FACEBOOK
}

type UserAccount {
  id: UserAccountId!
  email: String!
  provider: UserAccountProvider!
  pictureUrl: String
  createdAt: String!
  updatedAt: String!
}

type UserSession {
  id: UserRefreshTokenId!
  ip: String
  userAgent: String
  createdAt: String!
  lastUsedAt: String!
  expiresAt: String!
  current: Boolean! @resolved
}

type User {
  id: UserId!
  firstName: String!
  lastName: String!
  email: String!
  pictureUrl: String
  birthday: String
  isEnabled: Boolean!
  createdAt: String!
  updatedAt: String!
  accounts: [UserAccount!] @resolved
  sessions: [UserSession!] @resolved
  emailSettings: UserEmailSettings @resolved
}

type PendingEmailChange {
  newEmail: String!
  expiredAt: String!
}

type UserEmailSettings {
  dailyNewItemNotification: Boolean!
}

union GetCurrentUserResult = User | UnauthorizedRejection | ForbiddenRejection | InternalErrorRejection

type SearchUsersOutput {
  users: [User!]!
}

type ClosestFriendsOutput {
  users: [User!]!
}

union SearchUsersResult =
  | SearchUsersOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union ClosestFriendsResult =
  | ClosestFriendsOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union GetPendingEmailChangeResult =
  | PendingEmailChange
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

input RegisterUserInput {
  firstname: String!
  lastname: String!
  email: String!
  password: String!
  birthday: String
}

input LinkUserToGoogleInput {
  code: String!
}

input UpdateUserProfileInput {
  firstname: String!
  lastname: String!
  birthday: String
}

input ChangeUserPasswordInput {
  oldPassword: String!
  newPassword: String!
}

input UpdateUserPictureFromAccountInput {
  accountId: UserAccountId!
}

input RequestEmailChangeInput {
  newEmail: String!
}

input ConfirmEmailChangeInput {
  newEmail: String!
  token: String!
}

input UpdateUserEmailSettingsInput {
  dailyNewItemNotification: Boolean!
}

input SendResetPasswordEmailInput {
  email: String!
}

input ResetPasswordInput {
  email: String!
  token: String!
  newPassword: String!
}

input RevokeSessionInput {
  sessionId: UserRefreshTokenId!
}

union RegisterUserResult =
  | User
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union LinkUserToGoogleResult =
  | UserAccount
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union UpdateUserProfileResult =
  | User
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union UnlinkCurrentUserAccountResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union ChangeUserPasswordResult =
  | VoidOutput
  | ValidationRejection
  | BusinessRuleRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union UpdateUserPictureFromAccountResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union RemoveUserPictureResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union RequestEmailChangeResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union ConfirmEmailChangeResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union UpdateUserEmailSettingsResult =
  | UserEmailSettings
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union SendResetPasswordEmailResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union ResetPasswordResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | InternalErrorRejection

union RevokeSessionResult =
  | VoidOutput
  | ValidationRejection
  | UnauthorizedRejection
  | ForbiddenRejection
  | NotFoundRejection
  | InternalErrorRejection

extend type Query {
  currentUser: GetCurrentUserResult!
  pendingEmailChange: GetPendingEmailChangeResult
  searchUsers(keyword: String!): SearchUsersResult!
  closestFriends(limit: Int): ClosestFriendsResult!
}

extend type Mutation {
  registerUser(input: RegisterUserInput!): RegisterUserResult!
  linkCurrentUserWithGoogle(input: LinkUserToGoogleInput!): LinkUserToGoogleResult!
  unlinkCurrentUserAccount(accountId: UserAccountId!): UnlinkCurrentUserAccountResult!
  updateUserProfile(input: UpdateUserProfileInput!): UpdateUserProfileResult!
  changeUserPassword(input: ChangeUserPasswordInput!): ChangeUserPasswordResult!
  updateUserPictureFromAccount(input: UpdateUserPictureFromAccountInput!): UpdateUserPictureFromAccountResult!
  removeUserPicture: RemoveUserPictureResult!
  requestEmailChange(input: RequestEmailChangeInput!): RequestEmailChangeResult!
  confirmEmailChange(input: ConfirmEmailChangeInput!): ConfirmEmailChangeResult!
  updateUserEmailSettings(input: UpdateUserEmailSettingsInput!): UpdateUserEmailSettingsResult!
  sendResetPasswordEmail(input: SendResetPasswordEmailInput!): SendResetPasswordEmailResult!
  resetPassword(input: ResetPasswordInput!): ResetPasswordResult!
  revokeSession(input: RevokeSessionInput!): RevokeSessionResult!
}
