export const REPOSITORIES = {
  EVENT: Symbol('EVENT_REPOSITORY'),
  EVENT_ATTENDEE: Symbol('EVENT_ATTENDEE_REPOSITORY'),
  SECRET_SANTA: Symbol('SECRET_SANTA_REPOSITORY'),
  SECRET_SANTA_USER: Symbol('SECRET_SANTA_USER_REPOSITORY'),
  USER: Symbol('USER_REPOSITORY'),
  USER_EMAIL_CHANGE_VERIFICATION: Symbol('USER_EMAIL_CHANGE_VERIFICATION_REPOSITORY'),
  USER_EMAIL_SETTING: Symbol('USER_EMAIL_SETTING_REPOSITORY'),
  USER_PASSWORD_VERIFICATION: Symbol('USER_PASSWORD_VERIFICATION_REPOSITORY'),
  USER_SOCIAL: Symbol('USER_SOCIAL_REPOSITORY'),
  WISHLIST: Symbol('WISHLIST_REPOSITORY'),
  WISHLIST_ITEM: Symbol('WISHLIST_ITEM_REPOSITORY'),
} as const satisfies Record<Uppercase<string>, symbol>
