export const ATTENDEE_REPOSITORY = Symbol('ATTENDEE_REPOSITORY')
export const EVENT_REPOSITORY = Symbol('EVENT_REPOSITORY')
export const SECRET_SANTA_REPOSITORY = Symbol('SECRET_SANTA_REPOSITORY')
export const SECRET_SANTA_USER_REPOSITORY = Symbol('SECRET_SANTA_USER_REPOSITORY')
