const EVENT = Symbol('EVENT_REPOSITORY')
const EVENT_ATTENDEE = Symbol('EVENT_ATTENDEE_REPOSITORY')
const SECRET_SANTA = Symbol('SECRET_SANTA_REPOSITORY')
const SECRET_SANTA_USER = Symbol('SECRET_SANTA_USER_REPOSITORY')
const USER = Symbol('USER_REPOSITORY')
const USER_EMAIL_SETTING = Symbol('USER_EMAIL_SETTING_REPOSITORY')
const USER_PASSWORD_VERIFICATION = Symbol('USER_PASSWORD_VERIFICATION_REPOSITORY')
const USER_SOCIAL = Symbol('USER_SOCIAL_REPOSITORY')
const WISHLIST = Symbol('WISHLIST_REPOSITORY')
const WISHLIST_ITEM = Symbol('WISHLIST_ITEM_REPOSITORY')

export const REPOSITORIES = {
  EVENT,
  EVENT_ATTENDEE,
  SECRET_SANTA,
  SECRET_SANTA_USER,
  USER,
  USER_EMAIL_SETTING,
  USER_PASSWORD_VERIFICATION,
  USER_SOCIAL,
  WISHLIST,
  WISHLIST_ITEM,
}
